In [1]:
# NumPy Basics - Day 2
import numpy as np

# 1) Create
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# 2) Slice
print("First 3 elements:", arr[:3])
print("Last 2 elements:", arr[-2:])

# 3) Reshape
matrix = np.arange(1, 10).reshape(3, 3)
print("3x3 Matrix:\n", matrix)

# 4) Dot product (manual)
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
manual_dot = v1[0]*v2[0] + v1[1]*v2[1] + v1[2]*v2[2]
print("Manual Dot Product:", manual_dot)

# 5) Dot product (NumPy)
numpy_dot = np.dot(v1, v2)
print("NumPy Dot Product:", numpy_dot)
print("Match:", manual_dot == numpy_dot)


Array: [1 2 3 4 5]
First 3 elements: [1 2 3]
Last 2 elements: [4 5]
3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Manual Dot Product: 32
NumPy Dot Product: 32
Match: True
